version: '3'
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
  migrate:
    image: migrate/migrate:latest
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    command:
      - migrate
      - -database
      - postgres://postgres:postgres@postgres:5432/my_database
      - -source
      - /migrations
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
  golang:
    build: .
    ports:
        - "8080:8080"
    depends_on:
      - postgres
      - migrate
      - redis
